BEGIN
   EXECUTE IMMEDIATE 'DROP USER bl_3nf CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/

CREATE USER bl_3nf IDENTIFIED BY bl_3nf
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp
PROFILE default;

GRANT connect TO bl_3nf;
GRANT resource TO bl_3nf;
GRANT CREATE SYNONYM TO bl_3nf;