-- create bl_3nf user
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\user\bl_3nf.sql"

-- create tables for bl_3nf
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_countries\ce_countries.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_cities\ce_cities.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_postal_codes\ce_postal_codes.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_streets\ce_streets.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_buildings\ce_buildings.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_users\ce_users.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_products\ce_products.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_shipping_couriers\ce_shipping_couriers.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_packaging_types\ce_packaging_types.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_invoices\ce_invoices.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_order_items\ce_order_items.sql"

-- create sequnces for bl_3nf
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_countries\ce_countries_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_cities\ce_cities_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_postal_codes\ce_postal_codes_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_streets\ce_streets_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_buildings\ce_buildings_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_users\ce_users_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_products\ce_products_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_shipping_couriers\ce_shipping_couriers_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_packaging_types\ce_packaging_types_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_invoices\ce_invoices_seq.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_order_items\ce_order_items_seq.sql"

-- create synonyms for bl_3nf tables
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_countries\ce_countries-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_cities\ce_cities-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_postal_codes\ce_postal_codes-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_streets\ce_streets-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_buildings\ce_buildings-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_users\ce_users-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_products\ce_products-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_shipping_couriers\ce_shipping_couriers-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_packaging_types\ce_packaging_types-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_invoices\ce_invoices-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_order_items\ce_order_items-synonym.sql"

-- create synonyms for bl_3nf sequnces
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_countries\ce_countries_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_cities\ce_cities_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_postal_codes\ce_postal_codes_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_streets\ce_streets_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_buildings\ce_buildings_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_users\ce_users_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_products\ce_products_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_shipping_couriers\ce_shipping_couriers_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_packaging_types\ce_packaging_types_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_invoices\ce_invoices_seq-synonym.sql"
@"D:\Artsemi_Dzmitryieu\Module4\Shared_Folder\BI_Lab_winter-spring_2018\_0. DWH\Projects\Artsemi_Dzmitryieu\dwso\bl_3nf\tables\ce_order_items\ce_order_items_seq-synonym.sql"
