BEGIN
   EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ce_users';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1432 THEN
         RAISE;
      END IF;
END;
/

CREATE PUBLIC SYNONYM ce_users FOR bl_3nf.ce_users;