BEGIN
   EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM dim_date';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1432 THEN
         RAISE;
      END IF;
END;
/

CREATE PUBLIC SYNONYM dim_date FOR bl_dm.dim_date;
