BEGIN
   EXECUTE IMMEDIATE 'DROP USER bl_dm CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/

CREATE USER bl_dm IDENTIFIED BY bl_dm
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp
PROFILE default;

GRANT connect TO bl_dm;
GRANT resource TO bl_dm;
GRANT CREATE SYNONYM TO bl_dm;